trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- bash: |
    npm install snyk
    npx snyk auth $(snykToken)
    npx snyk monitor --all-projects
  displayName: 'Snyk SCA Bash Test'
  
- task: SnykSecurityScan@1
  displayName: 'Snyk SAST test'
  inputs:
    serviceConnectionEndpoint: 'snykToken'
    testType: 'app'
    severityThreshold: 'low'
    monitorWhen: 'never'
    failOnIssues: false
    additionalArguments: '--code'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykToken'
    testType: 'app'
    severityThreshold: 'high'
    monitorWhen: 'never'
    failOnIssues: false
    additionalArguments: '--all-projects'

